### ISSUE TITLE
Why don't we have `import_dataset.sh` inside pyiron?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron-publication-template#18]
https://github.com/pyiron/pyiron-publication-template/blob/f93ceddad4cc23c7858e16300126a96eff2bf2dd/.github/ci_support/import_dataset.sh#L1-L13

I think this functionality is useful in a general way. Why don't we have it inside the standard pyiron package?

**Comment by samwaseda** [comment]
Ah sorry I just saw that `pack` and `unpack` were solidly available inside pyiron XD. I guess it's a super nice feature that we should promote more.

**Comment by jan-janssen** [comment]
Yes, the rest is just some magic to copy any file no matter the file name.
